name: cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  shared: 
    path: '../shared'
  http: ^1.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
